package dev.newal.code.lite;

import org.json.JSONObject;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import static org.junit.Assert.*;

public class CandidateSelectionTest {
    private static final String ID = "0123456789abcdef01234567";
    private static final String BUILD = "0.1.42/1700000000000";
    // Generated by connectors.evolution.digest(newal_code), including pathlib component ordering.
    private static final String DIGEST = "c0499b8daba2e970fb47419780d46f32ef0f0e90fbf4c35a2d1b80aed2af69ac";

    @Rule public final TemporaryFolder temporary = new TemporaryFolder();

    @Test public void verifiedCandidateMatchesPythonUnicodeAndPathOrderingDigest() throws Exception {
        Fixture fixture = fixture();
        assertEquals(fixture.candidate.getCanonicalFile(), CandidateSelection.select(fixture.home, BUILD));
    }

    @Test public void missingAndMalformedMarkersFallBack() throws Exception {
        File empty = temporary.newFolder();
        assertNull(CandidateSelection.select(empty, BUILD));
        assertFalse(new File(empty, ".newal-code").exists());
        Fixture fixture = fixture();
        write(new File(fixture.evolution, "active.json"), "not json");
        assertNull(CandidateSelection.select(fixture.home, BUILD));
    }

    @Test public void uncheckedRootImportsFallBackButTestHomeIsAllowed() throws Exception {
        Fixture fixture = fixture();
        write(new File(fixture.candidate, "test-home/check.txt"), "check output");
        assertEquals(fixture.candidate.getCanonicalFile(), CandidateSelection.select(fixture.home, BUILD));
        write(new File(fixture.candidate, "sitecustomize.py"), "print('outside verified digest')");
        assertNull(CandidateSelection.select(fixture.home, BUILD));
    }

    @Test public void missingMalformedAndUnverifiedRecordsFallBack() throws Exception {
        for (String status : new String[] {"prepared", "failed", "Verified", ""}) {
            Fixture fixture = fixture();
            fixture.record.put("status", status);
            fixture.save();
            assertNull(status, CandidateSelection.select(fixture.home, BUILD));
        }
        Fixture fixture = fixture();
        write(new File(fixture.evolution, ID + ".json"), "[]");
        assertNull(CandidateSelection.select(fixture.home, BUILD));
        Files.delete(new File(fixture.evolution, ID + ".json").toPath());
        assertNull(CandidateSelection.select(fixture.home, BUILD));
    }

    @Test public void changedAddedDeletedAndRenamedEngineFilesInvalidateEvidence() throws Exception {
        Fixture changed = fixture();
        write(new File(changed.candidate, "newal_code/server.py"), "print('tampered')\n");
        assertNull(CandidateSelection.select(changed.home, BUILD));
        Fixture added = fixture();
        write(new File(added.candidate, "newal_code/new.py"), "extra\n");
        assertNull(CandidateSelection.select(added.home, BUILD));
        Fixture deleted = fixture();
        Files.delete(new File(deleted.candidate, "newal_code/a.py").toPath());
        assertNull(CandidateSelection.select(deleted.home, BUILD));
        Fixture renamed = fixture();
        Files.move(new File(renamed.candidate, "newal_code/a.py").toPath(),
                new File(renamed.candidate, "newal_code/b.py").toPath());
        assertNull(CandidateSelection.select(renamed.home, BUILD));
    }

    @Test public void ignoredCachesAndGitFilesDoNotAlterPythonDigest() throws Exception {
        Fixture fixture = fixture();
        write(new File(fixture.candidate, "newal_code/__pycache__/server.pyc"), "cached");
        write(new File(fixture.candidate, "newal_code/a/.git/index"), "git metadata");
        assertEquals(fixture.candidate.getCanonicalFile(), CandidateSelection.select(fixture.home, BUILD));
    }

    @Test public void missingOrDifferentBuildInEitherEvidenceFileFallsBack() throws Exception {
        for (boolean active : new boolean[] {true, false}) {
            for (Object build : new Object[] {JSONObject.NULL, "", "older-build", 42}) {
                Fixture fixture = fixture();
                JSONObject evidence = active ? fixture.active : fixture.record;
                if (build == JSONObject.NULL) evidence.remove("packaged_build");
                else evidence.put("packaged_build", build);
                fixture.save();
                assertNull(CandidateSelection.select(fixture.home, BUILD));
            }
        }
        Fixture fixture = fixture();
        assertNull(CandidateSelection.select(fixture.home, null));
        assertNull(CandidateSelection.select(fixture.home, ""));
        assertNull(CandidateSelection.select(fixture.home, "new-build"));
    }

    @Test public void invalidOrMismatchedIdsFallBack() throws Exception {
        for (Object id : new Object[] {ID.toUpperCase(), "../" + ID, ID + "0", ID.substring(1),
                "g123456789abcdef01234567", 123, JSONObject.NULL}) {
            Fixture fixture = fixture();
            fixture.active.put("id", id);
            fixture.save();
            assertNull(String.valueOf(id), CandidateSelection.select(fixture.home, BUILD));
        }
        Fixture fixture = fixture();
        fixture.record.put("id", "fedcba9876543210fedcba98");
        fixture.save();
        assertNull(CandidateSelection.select(fixture.home, BUILD));
    }

    @Test public void pathMustExactlyNameCandidateFromId() throws Exception {
        Fixture fixture = fixture();
        for (Object path : new Object[] {fixture.candidate.getAbsolutePath() + "/.",
                fixture.candidate.getAbsolutePath() + "/../" + ID,
                fixture.candidate.getParent(), new File(fixture.candidate, "newal_code").getPath(),
                temporary.newFolder().getPath(), "candidates/" + ID, JSONObject.NULL, 123}) {
            fixture.active.put("path", path);
            fixture.save();
            assertNull(String.valueOf(path), CandidateSelection.select(fixture.home, BUILD));
        }
    }

    @Test public void missingOrMalformedDigestFallsBack() throws Exception {
        for (Object digest : new Object[] {JSONObject.NULL, "", DIGEST.toUpperCase(),
                "0000000000000000000000000000000000000000000000000000000000000000", 123}) {
            Fixture fixture = fixture();
            fixture.record.put("verified_digest", digest);
            fixture.save();
            assertNull(CandidateSelection.select(fixture.home, BUILD));
        }
    }

    @Test public void engineRequiresPackageAndServer() throws Exception {
        for (String file : new String[] {"__init__.py", "server.py"}) {
            Fixture fixture = fixture();
            Files.delete(new File(fixture.candidate, "newal_code/" + file).toPath());
            assertNull(CandidateSelection.select(fixture.home, BUILD));
        }
    }

    @Test public void symlinkedEvidenceOrCandidateParentsFallBack() throws Exception {
        for (String relative : new String[] {".newal-code", ".newal-code/evolution",
                ".newal-code/evolution/candidates", ".newal-code/evolution/candidates/" + ID,
                ".newal-code/evolution/active.json", ".newal-code/evolution/" + ID + ".json"}) {
            Fixture fixture = fixture();
            File original = new File(fixture.home, relative);
            File moved = new File(temporary.newFolder(), "moved");
            Files.move(original.toPath(), moved.toPath());
            Files.createSymbolicLink(original.toPath(), moved.toPath());
            assertNull(relative, CandidateSelection.select(fixture.home, BUILD));
        }
    }

    @Test public void symlinksAnywhereInCandidateIncludingIgnoredDirectoriesFallBack() throws Exception {
        for (String relative : new String[] {"newal_code/server.py", "newal_code/a",
                "newal_code/__pycache__/ignored.pyc", "newal_code/.git/link", "sibling"}) {
            Fixture fixture = fixture();
            File link = new File(fixture.candidate, relative);
            Files.createDirectories(link.getParentFile().toPath());
            File target = new File(temporary.newFolder(), "target");
            if (link.exists()) Files.move(link.toPath(), target.toPath());
            else write(target, "link content");
            Files.createSymbolicLink(link.toPath(), target.toPath());
            assertNull(relative, CandidateSelection.select(fixture.home, BUILD));
        }
    }

    @Test public void danglingSymlinkAndSymlinkedEngineFallBack() throws Exception {
        Fixture dangling = fixture();
        Files.createSymbolicLink(new File(dangling.candidate, "dangling").toPath(),
                new File(dangling.candidate, "missing").toPath());
        assertNull(CandidateSelection.select(dangling.home, BUILD));
        Fixture fixture = fixture();
        File engine = new File(fixture.candidate, "newal_code");
        File moved = new File(temporary.newFolder(), "engine");
        Files.move(engine.toPath(), moved.toPath());
        Files.createSymbolicLink(engine.toPath(), moved.toPath());
        assertNull(CandidateSelection.select(fixture.home, BUILD));
    }


    @Test public void compatibleUpdateSurvivesRestartAndNeedsNativeHealthConfirmation() throws Exception {
        Fixture fixture = updateFixture("43", "activating", false);
        assertEquals(fixture.candidate.getCanonicalFile(),
                CandidateSelection.select(fixture.home, "42", Setup.UPDATE_COMPAT));
        assertTrue(CandidateSelection.markHealthy(fixture.home, "42", Setup.UPDATE_COMPAT));
        JSONObject active = json(new File(fixture.evolution, "active.json"));
        assertEquals("active", active.getString("state"));
        assertTrue(active.getBoolean("health_confirmed"));
        // A second selection models a later process/app restart: the same verified
        // revision remains selected only because its digest/evidence still validates.
        assertEquals(fixture.candidate.getCanonicalFile(),
                CandidateSelection.select(fixture.home, "42", Setup.UPDATE_COMPAT));
    }

    @Test public void failedActivationRollsBackToPackagedEngineAndRecordsFailure() throws Exception {
        Fixture fixture = updateFixture("43", "activating", false);
        assertTrue(CandidateSelection.rollbackPending(
                fixture.home, "42", Setup.UPDATE_COMPAT, "startup probe failed"));
        assertFalse(new File(fixture.evolution, "active.json").exists());
        assertNull(CandidateSelection.select(fixture.home, "42", Setup.UPDATE_COMPAT));
        JSONObject failure = json(new File(fixture.evolution, "last-failure.json"));
        assertEquals("rolled_back", failure.getString("state"));
        assertEquals("failed_activation", failure.getString("cause"));
        assertEquals(ID, failure.getString("failed_revision"));
        assertEquals("startup probe failed", failure.getString("error"));
    }

    @Test public void healthyActiveRevisionIsNeverRolledBackByLaterTransientFailure() throws Exception {
        Fixture fixture = updateFixture("43", "active", true);
        assertFalse(CandidateSelection.rollbackPending(
                fixture.home, "42", Setup.UPDATE_COMPAT, "later transient failure"));
        assertEquals(fixture.candidate.getCanonicalFile(),
                CandidateSelection.select(fixture.home, "42", Setup.UPDATE_COMPAT));
    }

    @Test public void olderUpdateNeedsExplicitDowngradeEvidenceInRecordAndPointer() throws Exception {
        Fixture denied = updateFixture("41", "activating", false);
        assertNull(CandidateSelection.select(denied.home, "42", Setup.UPDATE_COMPAT));

        Fixture allowed = updateFixture("41", "activating", false);
        allowed.active.put("downgrade_allowed", true);
        allowed.record.put("downgrade_allowed", true);
        allowed.save();
        assertEquals(allowed.candidate.getCanonicalFile(),
                CandidateSelection.select(allowed.home, "42", Setup.UPDATE_COMPAT));
    }

    @Test public void updateWithWrongNativeCompatibilityFallsBackToPackagedEngine() throws Exception {
        Fixture fixture = updateFixture("43", "activating", false);
        assertNull(CandidateSelection.select(fixture.home, "42", "different-native-abi"));
        fixture.record.put("compatibility_id", "different-native-abi");
        fixture.save();
        assertNull(CandidateSelection.select(fixture.home, "42", Setup.UPDATE_COMPAT));
    }

    private Fixture updateFixture(String version, String state, boolean healthy) throws Exception {
        Fixture fixture = fixture();
        int versionCode = Integer.parseInt(version);
        fixture.active.put("kind", "update")
                .put("state", state)
                .put("health_confirmed", healthy)
                .put("compatibility_id", Setup.UPDATE_COMPAT)
                .put("version_code", versionCode)
                .put("verified_digest", DIGEST);
        fixture.record.put("kind", "update")
                .put("status", "ready_to_activate")
                .put("compatibility_id", Setup.UPDATE_COMPAT)
                .put("version_code", versionCode);
        fixture.save();
        return fixture;
    }

    private static JSONObject json(File file) throws Exception {
        return new JSONObject(new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8));
    }

    private Fixture fixture() throws Exception {
        File home = temporary.newFolder();
        File evolution = new File(home, ".newal-code/evolution");
        File candidate = new File(evolution, "candidates/" + ID);
        write(new File(candidate, "newal_code/__init__.py"), "# engine\n");
        write(new File(candidate, "newal_code/server.py"), "print(\"verified\")\n");
        write(new File(candidate, "newal_code/a/z.py"), "nested\n");
        write(new File(candidate, "newal_code/a.py"), "flat\n");
        write(new File(candidate, "newal_code/café/مرحبا.py"), "مرحبا\n");
        write(new File(candidate, "newal_code/\ue000.py"), "private\n");
        write(new File(candidate, "newal_code/😀.py"), "emoji\n");
        JSONObject active = new JSONObject().put("id", ID).put("path", candidate.getAbsolutePath())
                .put("packaged_build", BUILD);
        JSONObject record = new JSONObject().put("id", ID).put("status", "verified")
                .put("verified_digest", DIGEST).put("packaged_build", BUILD);
        write(new File(evolution, "active.json"), active.toString());
        write(new File(evolution, ID + ".json"), record.toString());
        return new Fixture(home, evolution, candidate, active, record);
    }

    private static void write(File file, String content) throws Exception {
        Files.createDirectories(file.getParentFile().toPath());
        Files.write(file.toPath(), content.getBytes(StandardCharsets.UTF_8));
    }

    private static final class Fixture {
        final File home, evolution, candidate;
        final JSONObject active, record;

        Fixture(File home, File evolution, File candidate, JSONObject active, JSONObject record) {
            this.home = home;
            this.evolution = evolution;
            this.candidate = candidate;
            this.active = active;
            this.record = record;
        }

        void save() throws Exception {
            write(new File(evolution, "active.json"), active.toString());
            write(new File(evolution, ID + ".json"), record.toString());
        }
    }
}
